# Generated by Django 3.1.2 on 2020-10-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.subreddit')),
                ('user_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('on_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.redditpost')),
                ('replied_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op', to='Post.comment')),
                ('user_commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
