# Generated by Django 3.1.2 on 2020-10-15 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        ('Post', '0002_auto_20201006_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditpost',
            name='sub',
        ),
        migrations.AddField(
            model_name='comment',
            name='dt_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-10-15 11:11:11.111111'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditpost',
            name='dt_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-10-15 11:11:11.111111'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditpost',
            name='subreddit_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subreddit_parent', to='Main.subreddit'),
        ),
    ]
