# Generated by Django 3.1.2 on 2020-10-15 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0003_auto_20201015_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replied_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, null=True, related_name='replied_comments', to='Post.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='users_voted',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redditpost',
            name='users_voted',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
