# Generated by Django 3.1.2 on 2020-10-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20201015_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='on_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.redditpost'),
        ),
    ]
