# Generated by Django 3.1.2 on 2020-10-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddituser',
            name='mod_permissions',
        ),
        migrations.AddField(
            model_name='reddituser',
            name='DisplayName',
            field=models.CharField(default='self', max_length=25),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='subreddits_moderated',
            field=models.ManyToManyField(blank=True, related_name='subreddits_moderated', to='Main.Subreddit'),
        ),
    ]
